
#### Proyecto II
##### Roberto Gonzalez Gomez
##### Programacion II BD-143
##### Sistema, en Python con Programación Orientada a Objetos, que ingesta datos de partidos de la Copa Mundial de la FIFA desde un archivo CSV, los procesa en memoria mediante estructuras y clases bien definidas, y permite consultas, análisis exploratorio (EDA) y visualización de gráficos.

##### Importamos primeramente todos los modulos necesarios

In [1]:
import pandas as pd
import numpy as np
import os

from ingesta.carga import CargadorDatos
from gestor.gestion import GestorPartidos
from eda.analisis_eda import ProcesadorEDA

#### 1.Ingesta de datos
##### Se establece un variable con el url de descarga de donde vamos a obtener el csv que se usara como parametro necesario en el objeto

In [2]:
url = "https://raw.githubusercontent.com/martj42/international_results/master/results.csv"

##### Creamos el objeto con los parametros necesarios los cuales son el url de descarga, las rutas donde se guardaran los archivos, primero crudo solo filtrado y luego procesado con limpieza y columnas derivadas

In [3]:
cargador = CargadorDatos(url, r"C:\world_cup_insights\data\raw", r"C:\world_cup_insights\data\processed")

##### Aplicamos el metodo descarga al objeto para que obtenga el csv desde el url y los convierta en un dataframe

In [4]:
cargador.descarga()
print('Descarga exitosa\n')

Descarga exitosa

##### Aplicamos el metodo filtro al objeto para que nos filtre el csv original solamente con el torneo de interes el FIFA World Cup

In [5]:
cargador.filtro()
print('Filtro aplicado al dataframe exitosamente\n')

Filtro aplicado al dataframe exitosamente

##### Finalmente guardamos el dataframe como un archivo csv en la ruta solicitada

In [6]:
cargador.guardar_raw()
print('Archivo guardado en carpeta /raw\n')

Archivo guardado en carpeta /raw

#### 2. Consultas con GestorPartidos

##### Creamos la variable df_mundial apartir del objeto cargador que sera el dataframe que usaremos en GestorPartido

In [7]:
df_mundial = cargador.filtro()

##### Creamos el objeto gestor apartir de la clase GestorPartido con el parametro df_mundial

In [8]:
gestor = GestorPartidos(df_mundial)

##### Probaremos los diferentes metodos de esta clase para verificar su funcionalidad
##### Empezando con el metodo get_partido donde procederemos a ver el primer partido en la historia de los mundiales y sus diferentes atributos

In [9]:
gestor.get_partido(1)

,id_partido,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1,1930-07-13,Belgium,United States,0,3,FIFA World Cup,Montevideo,Uruguay,True

##### Mediante el metodo get_equipo podemos ver todas las apariciones del equipo seleccionado en todos los mundiales que participo, seleccionaremos a Costa Rica como ejemplo

In [10]:
gestor.get_por_equipo('Costa Rica')

,id_partido,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
419,420,1990-06-11,Costa Rica,Scotland,1,0,FIFA World Cup,Genoa,Italy,True
430,431,1990-06-16,Brazil,Costa Rica,1,0,FIFA World Cup,Turin,Italy,True
443,444,1990-06-20,Sweden,Costa Rica,1,2,FIFA World Cup,Genoa,Italy,True
449,450,1990-06-23,Czechoslovakia,Costa Rica,4,1,FIFA World Cup,Bari,Italy,True
591,592,2002-06-04,China,Costa Rica,0,2,FIFA World Cup,Gwangju,South Korea,True
606,607,2002-06-09,Costa Rica,Turkey,1,1,FIFA World Cup,Incheon,South Korea,True
620,621,2002-06-13,Costa Rica,Brazil,2,5,FIFA World Cup,Suwon,South Korea,True
644,645,2006-06-09,Germany,Costa Rica,4,2,FIFA World Cup,Munich,Germany,False
661,662,2006-06-15,Ecuador,Costa Rica,3,0,FIFA World Cup,Hamburg,Germany,True
676,677,2006-06-20,Costa Rica,Poland,1,2,FIFA World Cup,Hanover,Germany,True
779,780,2014-06-14,Uruguay,Costa Rica,1,3,FIFA World Cup,Fortaleza,Brazil,True
796,797,2014-06-20,Italy,Costa Rica,0,1,FIFA World Cup,Recife,Brazil,True
808,809,2014-06-24,Costa Rica,England,0,0,FIFA World Cup,Belo Horizonte,Brazil,True
822,823,2014-06-29,Costa Rica,Greece,1,1,FIFA World Cup,Recife,Brazil,True
831,832,2014-07-05,Netherlands,Costa Rica,0,0,FIFA World Cup,Salvador,Brazil,True
844,845,2018-06-17,Costa Rica,Serbia,0,1,FIFA World Cup,Samara,Russia,True
859,860,2018-06-22,Brazil,Costa Rica,2,0,FIFA World Cup,Saint Petersburg,Russia,True
879,880,2018-06-27,Switzerland,Costa Rica,2,2,FIFA World Cup,Nizhny Novgorod,Russia,True
909,910,2022-11-23,Spain,Costa Rica,7,0,FIFA World Cup,Doha,Qatar,True
924,925,2022-11-27,Japan,Costa Rica,0,1,FIFA World Cup,Al Rayyan,Qatar,True
941,942,2022-12-01,Costa Rica,Germany,2,4,FIFA World Cup,Al Khor,Qatar,True

##### Tambien podemos ver por anio todos los partidos de ese mundial en especifico, usaremos el de 2022 como ejemplo

In [11]:
gestor.get_por_anio(2022)

,id_partido,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
900,901,2022-11-20,Qatar,Ecuador,0,2,FIFA World Cup,Al Khor,Qatar,False
901,902,2022-11-21,Senegal,Netherlands,0,2,FIFA World Cup,Doha,Qatar,True
902,903,2022-11-21,England,Iran,6,2,FIFA World Cup,Al Rayyan,Qatar,True
903,904,2022-11-21,United States,Wales,1,1,FIFA World Cup,Al Rayyan,Qatar,True
904,905,2022-11-22,Argentina,Saudi Arabia,1,2,FIFA World Cup,Lusail,Qatar,True
...,...,...,...,...,...,...,...,...,...,...
959,960,2022-12-10,England,France,1,2,FIFA World Cup,Al Khor,Qatar,True
960,961,2022-12-13,Argentina,Croatia,3,0,FIFA World Cup,Lusail,Qatar,True
961,962,2022-12-14,France,Morocco,2,0,FIFA World Cup,Al Khor,Qatar,True
962,963,2022-12-17,Croatia,Morocco,2,1,FIFA World Cup,Al Rayyan,Qatar,True
963,964,2022-12-18,Argentina,France,3,3,FIFA World Cup,Lusail,Qatar,True

##### Mediante el metodo get_por_sede podemos ver todos los partidos celebrados en determinada sede, veremos como ejemplo a Alemania

In [12]:
gestor.get_por_sede('Germany')

,id_partido,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
232,233,1974-06-13,Brazil,Yugoslavia,0,0,FIFA World Cup,Frankfurt,Germany,True
233,234,1974-06-14,DR Congo,Scotland,0,2,FIFA World Cup,Dortmund,Germany,True
234,235,1974-06-14,German DR,Australia,2,0,FIFA World Cup,Hamburg,Germany,True
235,236,1974-06-14,Germany,Chile,1,0,FIFA World Cup,Berlin,Germany,False
236,237,1974-06-15,Italy,Haiti,3,1,FIFA World Cup,Munich,Germany,True
...,...,...,...,...,...,...,...,...,...,...
703,704,2006-07-01,England,Portugal,0,0,FIFA World Cup,Gelsenkirchen,Germany,True
704,705,2006-07-04,Germany,Italy,0,2,FIFA World Cup,Dortmund,Germany,False
705,706,2006-07-05,Portugal,France,0,1,FIFA World Cup,Munich,Germany,True
706,707,2006-07-08,Germany,Portugal,3,1,FIFA World Cup,Stuttgart,Germany,False
707,708,2006-07-09,Italy,France,1,1,FIFA World Cup,Berlin,Germany,True

##### El metodo ventaja_local nos permite ver en porcentajes si los equipos locales han tenido alguna ventaja segun la proporcion de perdidas empates y victorias, donde claramente vemos que la localia juega un papel determinante a nivel de todos los mundiales con un casi 62%

In [13]:
gestor.ventaja_local()

local        61.194030
visitante    21.641791
empate       17.164179
Name: proportion, dtype: float64

##### Podemos ver todos los enfrentamientos directos entre selecciones con el metodo get_enfrentamiento_directo que nos brinda todos los partidos entre esos dos equipos, usaremos a Costa Rica y Brazil como ejemplo

In [14]:
gestor.get_enfrentamientos_directos('Brazil', 'Costa Rica')

,id_partido,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
430,431,1990-06-16,Brazil,Costa Rica,1,0,FIFA World Cup,Turin,Italy,True
620,621,2002-06-13,Costa Rica,Brazil,2,5,FIFA World Cup,Suwon,South Korea,True
859,860,2018-06-22,Brazil,Costa Rica,2,0,FIFA World Cup,Saint Petersburg,Russia,True

##### Por ultimo tenemos el metodo get_campeones que nos brinda los nombres de todos los campeones de todas las ediciones de mundiales

In [15]:
gestor.get_campeones()

      anio    campeon
17    1930    Uruguay
34    1934      Italy
51    1938     Brazil
73    1950    Uruguay
100   1954    Germany
135   1958     Brazil
167   1962     Brazil
199   1966    England
231   1970     Brazil
269   1974    Germany
307   1978  Argentina
359   1982      Italy
411   1986  Argentina
463   1990    Germany
515   1994      Italy
579   1998     France
643   2002     Brazil
707   2006     France
771   2010      Spain
835   2014    Germany
899   2018     France
963   2022     France
1067  2026      Spain

#### 3. Analisis Exploratorio
##### Empezaremos esta etapa con la limpieza de datos

##### Creamos el objeto primeramente

In [16]:
procesador = ProcesadorEDA(df_mundial)

##### Le aplicamos el metodo limpieza datos que eliminara duplicados en caso de haber, se manejaran los nulos eliminandolos ya que al casi no haber no afectan en gran manera el analisis y convertira el formato de algunas columnas para hacer el dataframe mas manejable, date de str a datetime, y home_score y away_score a int

In [17]:
# Contamos filas completamente idénticas
duplicados = df_mundial.duplicated().sum()
print(f"Cantidad de registros duplicados detectados: {duplicados}")

# Contamos nulos por columna (esto respalda lo que pusiste en tu texto)
print("\nValores nulos por columna:")
print(df_mundial.isnull().sum())

Cantidad de registros duplicados detectados: 0

Valores nulos por columna:
id_partido    0
date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
dtype: int64

##### Como no tenemos duplicados ni nulos entonces no aplica

In [18]:
procesador.limpieza_datos()

,id_partido,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1,1930-07-13,Belgium,United States,0,3,FIFA World Cup,Montevideo,Uruguay,True
1,2,1930-07-13,France,Mexico,4,1,FIFA World Cup,Montevideo,Uruguay,True
2,3,1930-07-14,Brazil,Yugoslavia,1,2,FIFA World Cup,Montevideo,Uruguay,True
3,4,1930-07-14,Peru,Romania,1,3,FIFA World Cup,Montevideo,Uruguay,True
4,5,1930-07-15,Argentina,France,1,0,FIFA World Cup,Montevideo,Uruguay,True
...,...,...,...,...,...,...,...,...,...,...
1063,1064,2026-07-11,Argentina,Switzerland,3,1,FIFA World Cup,Kansas City,United States,True
1064,1065,2026-07-14,France,Spain,0,2,FIFA World Cup,Arlington,United States,True
1065,1066,2026-07-15,England,Argentina,1,2,FIFA World Cup,Atlanta,United States,True
1066,1067,2026-07-18,France,England,4,6,FIFA World Cup,Miami Gardens,United States,True
1067,1068,2026-07-19,Spain,Argentina,1,0,FIFA World Cup,East Rutherford,United States,True

##### Agregamos algunas columnas derivadas para enriquecer el dataframe con columnas de anio, total de goles, diferencia de goles y el ganador

In [19]:
procesador.agregar_columnas_derivadas()

,id_partido,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,anio,total_goles,diferencia_goles,ganador
0,1,1930-07-13,Belgium,United States,0,3,FIFA World Cup,Montevideo,Uruguay,True,1930,3,3,Visitante
1,2,1930-07-13,France,Mexico,4,1,FIFA World Cup,Montevideo,Uruguay,True,1930,5,3,Local
2,3,1930-07-14,Brazil,Yugoslavia,1,2,FIFA World Cup,Montevideo,Uruguay,True,1930,3,1,Visitante
3,4,1930-07-14,Peru,Romania,1,3,FIFA World Cup,Montevideo,Uruguay,True,1930,4,2,Visitante
4,5,1930-07-15,Argentina,France,1,0,FIFA World Cup,Montevideo,Uruguay,True,1930,1,1,Local
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,1064,2026-07-11,Argentina,Switzerland,3,1,FIFA World Cup,Kansas City,United States,True,2026,4,2,Local
1064,1065,2026-07-14,France,Spain,0,2,FIFA World Cup,Arlington,United States,True,2026,2,2,Visitante
1065,1066,2026-07-15,England,Argentina,1,2,FIFA World Cup,Atlanta,United States,True,2026,3,1,Visitante
1066,1067,2026-07-18,France,England,4,6,FIFA World Cup,Miami Gardens,United States,True,2026,10,2,Visitante
1067,1068,2026-07-19,Spain,Argentina,1,0,FIFA World Cup,East Rutherford,United States,True,2026,1,1,Local

##### Generamos un resumen descriptivo con estadisticas basicas de las diferentes columnas cuantitativas y cualitativas, donde podermos observar tipos de datos, media, cuartiles, desviacion estandar asi como la moda

In [20]:
procesador.resumen_descriptivo()

<class 'pandas.DataFrame'>
RangeIndex: 1068 entries, 0 to 1067
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_partido        1068 non-null   int64
 1   date              1068 non-null   datetime64[us]
 2   home_team         1068 non-null   str
 3   away_team         1068 non-null   str
 4   home_score        1068 non-null   int64
 5   away_score        1068 non-null   int64
 6   tournament        1068 non-null   str
 7   city              1068 non-null   str
 8   country           1068 non-null   str
 9   neutral           1068 non-null   bool
 10  anio              1068 non-null   int32
 11  total_goles       1068 non-null   int64
 12  diferencia_goles  1068 non-null   int64
 13  ganador           1068 non-null   str
dtypes: bool(1), datetime64[us](1), int32(1), int64(5), str(6)
memory usage: 160.0 KB
None

(                             date   home_score   away_score         anio  \
 count                        1068  1068.000000  1068.000000  1068.000000
 mean   1993-04-26 21:18:12.134831     1.583333     1.251873  1992.823970
 min           1930-07-13 00:00:00     0.000000     0.000000  1930.000000
 25%           1974-07-03 00:00:00     0.750000     0.000000  1974.000000
 50%           1998-06-16 12:00:00     1.000000     1.000000  1998.000000
 75%           2014-06-21 06:00:00     2.000000     2.000000  2014.000000
 max           2026-07-19 00:00:00    10.000000     8.000000  2026.000000
 std                           NaN     1.494000     1.292051    25.285083

        total_goles  diferencia_goles
 count  1068.000000       1068.000000
 mean      2.835206          1.500000
 min       0.000000          0.000000
 25%       1.000000          1.000000
 50%       3.000000          1.000000
 75%       4.000000          2.000000
 max      12.000000          9.000000
 std       1.920880          1.403904  ,
        home_team away_team      tournament         city        country ganador
 count       1068      1068            1068         1068           1068    1068
 unique        84        84               1          179             19       3
 top       Brazil   Uruguay  FIFA World Cup  Mexico City  United States   Local
 freq          91        40            1068           28            130     488,
 1068,
 (np.int32(1930), np.int32(2026)),
         date home_team away_team  home_score  away_score      tournament  \
 0 1934-05-27    Brazil   Uruguay         1.0         1.0  FIFA World Cup
 1 1958-06-08       NaN       NaN         NaN         NaN             NaN
 2 1958-06-15       NaN       NaN         NaN         NaN             NaN

           city        country neutral    anio  total_goles  diferencia_goles  \
 0  Mexico City  United States    True  2026.0          3.0               1.0
 1          NaN            NaN     NaN     NaN          NaN               NaN
 2          NaN            NaN     NaN     NaN          NaN               NaN

   ganador
 0   Local
 1     NaN
 2     NaN  )

##### Tambien se tenemos el metodo matriz_correlacion donde vemos la correlacion entre las diferentes variables numericas

In [21]:
procesador.matriz_correlacion()

,home_score,away_score,anio,total_goles,diferencia_goles
home_score,1.000000,-0.054823,-0.123139,0.740893,0.556980
away_score,-0.054823,1.000000,-0.146984,0.629995,0.251880
anio,-0.123139,-0.146984,1.000000,-0.194640,-0.138662
total_goles,0.740893,0.629995,-0.194640,1.000000,0.602625
diferencia_goles,0.556980,0.251880,-0.138662,0.602625,1.000000

##### Con el metodo deteccion_outlier podemos ver lo valores atipicos de determinada columna numerica, usaremos total goles de ejemplo

In [22]:
procesador.deteccion_outliers('total_goles')

9        9
36      11
81       9
88      11
91       9
94      12
105     10
134      9
243      9
311     11
1066    10
Name: total_goles, dtype: int64

##### Aca vemos el numero de fila y especificamente los datos atipicos que aparecen y se repiten dentro del dataframe y especificamente la columna total de goles

##### Finalmente podremos observar con el metodo agrupacion_por_edicion diferentes datos estadisticos como total de goles, promedio de goles por partido y partidos jugados por cada anio de mundial

In [23]:
procesador.agrupacion_por_edicion()

      total_goles_edicion  promedio_goles_partido  partidos_jugados
anio
1930                   70                3.888889                18
1934                   70                4.117647                17
1938                   84                4.666667                18
1950                   88                4.000000                22
1954                  140                5.384615                26
1958                  126                3.600000                35
1962                   89                2.781250                32
1966                   89                2.781250                32
1970                   95                2.968750                32
1974                   97                2.552632                38
1978                  102                2.684211                38
1982                  146                2.807692                52
1986                  132                2.538462                52
1990                  115                2.211538                52
1994                  141                2.711538                52
1998                  171                2.671875                64
2002                  161                2.515625                64
2006                  147                2.296875                64
2010                  145                2.265625                64
2014                  171                2.671875                64
2018                  169                2.640625                64
2022                  172                2.687500                64
2026                  308                2.961538               104